#!/bin/bash

__FILE__=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
__DIR__=$(dirname "${__FILE__}")
. $__DIR__/common.inc

NAME=ffmpeg
VERSION=4.3.1

do_download()
{
  info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! wget http://ffmpeg.org/releases/ffmpeg-${VERSION}.tar.bz2 -O ffmpeg-${VERSION}.tar.bz2; then
    error "Failed to download $NAME"
  fi
  info "Download complete"
}

do_unpack()
{
  info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! tar xjvf ffmpeg-${VERSION}.tar.bz2; then
    error "Failed to unpack $NAME"
  fi
  info "Unpack complete"
}

do_configure()
{
  info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src ffmpeg-${VERSION}
  if ! PKG_CONFIG_PATH="$BUILD_DIR/lib/pkgconfig" ./configure \
    --prefix="$BUILD_DIR" \
    --pkg-config-flags="--static" \
    --extra-cflags="-I$BUILD_DIR/include" \
    --extra-ldflags="-L$BUILD_DIR/lib" \
    --extra-libs="-lpthread -lm" \
    --bindir="$BIN_DIR" \
    --enable-gpl \
    --enable-openssl \
    --enable-libass \
    --enable-libfdk-aac \
    --enable-libfreetype \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libtheora \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libzvbi \
    --enable-nonfree
  then
    error "Failed to configure $NAME"
  fi
  info "Configuration complete"
}

do_compile()
{
  info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  if [ -f "/proc/cpuinfo" ]; then
    COMPILE_ARGS="-j$(grep -c ^processor /proc/cpuinfo)"
  fi
  cd_src ffmpeg-${VERSION}
  if ! make $COMPILE_ARGS; then
    error "Failed to compile $NAME"
  fi
  info "Compilation complete"
}

do_install()
{
  info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src ffmpeg-${VERSION}
  if ! make install; then
    error "Failed to install $NAME"
  fi
  run hash -r
  info "Installation complete"
}

do_clean()
{
  info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src ffmpeg-${VERSION}
  if ! make distclean; then
    error "Failed to clean $NAME"
  fi
  info "Clean complete"
}

main $*
