#!/bin/bash

__FILE__=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
__DIR__=$(dirname "${__FILE__}")
. $__DIR__/common.inc

NAME=libaom
VERSION=3.4.0

do_download()
{
  info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! wget https://aomedia.googlesource.com/aom/+archive/refs/tags/v${VERSION}.tar.gz -O libaom-${VERSION}.tar.gz; then
    error "Failed to download $NAME"
  fi
  info "Download complete"
}

do_unpack()
{
  info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! mkdir -p libaom-${VERSION}; then
    error "Failed to create libaom-${VERSION} directory"
  fi
  if ! tar xzvf libaom-${VERSION}.tar.gz --directory libaom-${VERSION}; then
    error "Failed to unpack $NAME"
  fi
  info "Unpack complete"
}

do_configure()
{
  info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src libaom-${VERSION}
  if ! mkdir -p aom_build; then
    error "Failed to create aom_build directory"
  fi
  cd_src libaom-${VERSION}/aom_build
  # TODO: findout why compile fail with -DCONFIG_TUNE_VMAF=1
  # -DCMAKE_PREFIX_PATH="$BUILD_DIR" : pass comfigure but fail compile
  # -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" : no effets
  if ! cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$BUILD_DIR" -DBUILD_SHARED_LIBS=0 -DENABLE_DOCS=0 -DENABLE_TESTS=0; then
    error "Failed to configure $NAME"
  fi
  info "Configuration complete"
}

do_compile()
{
  info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  if [ -f "/proc/cpuinfo" ]; then
    COMPILE_ARGS="-j$(grep -c ^processor /proc/cpuinfo)"
  fi
  cd_src libaom-${VERSION}/aom_build
  if ! make $COMPILE_ARGS; then
    error "Failed to compile $NAME"
  fi
  info "Compilation complete"
}

do_install()
{
  info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src libaom-${VERSION}/aom_build
  if ! make install; then
    error "Failed to install $NAME"
  fi
  info "Installation complete"
}

do_clean()
{
  info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src libaom-${VERSION}
  if ! rm -rf ./aom_build; then
    error "Failed to clean $NAME"
  fi
  info "Clean complete"
}

main $*
