#!/bin/bash

__FILE__=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
__DIR__=$(dirname "${__FILE__}")
. $__DIR__/common.inc

NAME=librist
VERSION=v0.2.7

do_download()
{
  info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! wget https://code.videolan.org/rist/librist/-/archive/${VERSION}/librist-${VERSION}.tar.bz2 -O librist-${VERSION}.tar.bz2; then
    error "Failed to download $NAME"
  fi
  info "Download complete"
}

do_unpack()
{
  info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! tar xjvf librist-${VERSION}.tar.bz2; then
    error "Failed to unpack $NAME"
  fi
  info "Unpack complete"
}

do_configure()
{
  info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src librist-${VERSION}
  if ! mkdir -p build; then
    error "Failed to create build directory"
  fi
  cd_src librist-${VERSION}/build
  if ! meson setup --default-library=static .. --prefix "$BUILD_DIR"; then
    error "Failed to configure $NAME"
  fi
  info "Configuration complete"
}

do_compile()
{
  info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src librist-${VERSION}/build
  # Note: include/vcs_version.h generation fatal error can be safely ignored
  if ! ninja; then
    error "Failed to compile $NAME"
  fi
  info "Compilation complete"
}

do_install()
{
  info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src librist-${VERSION}/build
  if ! ninja install; then
    error "Failed to install $NAME"
  fi
  info "Installation complete"
}

do_clean()
{
  info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src librist-${VERSION}
  if ! rm -rf ./build; then
    error "Failed to clean $NAME"
  fi
  info "Clean complete"
}

main $*
