#!/bin/bash

__FILE__=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
__DIR__=$(dirname "${__FILE__}")
. $__DIR__/common.inc

NAME=yasm
VERSION=1.3.0

do_download()
{
  info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! wget http://www.tortall.net/projects/yasm/releases/yasm-${VERSION}.tar.gz -O yasm-${VERSION}.tar.gz; then
    error "Failed to download $NAME"
  fi
  info "Download complete"
}

do_unpack()
{
  info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! tar xzvf yasm-${VERSION}.tar.gz; then
    error "Failed to unpack $NAME"
  fi
  info "Unpack complete"
}

do_configure()
{
  info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src yasm-${VERSION}
  if ! ./configure --prefix="$BUILD_DIR" --bindir="$BIN_DIR"; then
    error "Failed to configure $NAME"
  fi
  info "Configuration complete"
}

do_compile()
{
  info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src yasm-${VERSION}
  if ! make; then
    error "Failed to compile $NAME"
  fi
  info "Compilation complete"
}

do_install()
{
  info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src yasm-${VERSION}
  if ! make install; then
    error "Failed to install $NAME"
  fi
  info "Installation complete"
}

do_clean()
{
  info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src yasm-${VERSION}
  if ! make distclean; then
    error "Failed to clean $NAME"
  fi
  info "Clean complete"
}

main $*
